"use client";
import Link from "next/link"; import { FormEvent, useEffect, useState } from "react"; import { getSupabaseBrowserClient } from "@/lib/supabase/browser"; import { services, budgetRanges } from "@/config/project";
type Project={id:string;title:string;status:string;service_type:string|null;city:string|null;updated_at:string};
const labels:Record<string,string>={draft:'Brouillon',submitted:'Dossier envoyé',received:'Dossier reçu',to_review:'À vérifier',waiting_for_information:'Informations attendues',under_analysis:'Analyse en cours',appointment_required:'Rendez-vous à programmer',appointment_confirmed:'Rendez-vous confirmé',proposal_in_progress:'Proposition en préparation',proposal_available:'Proposition disponible',changes_requested:'Modifications demandées',approved:'Projet validé',completed:'Projet terminé',archived:'Archivé'};
export function ClientSpace(){const[loading,setLoading]=useState(true);const[userName,setUserName]=useState('');const[projects,setProjects]=useState<Project[]>([]);const[show,setShow]=useState(false);const[title,setTitle]=useState('');const[service,setService]=useState(services[0]);const[city,setCity]=useState('');const[budget,setBudget]=useState(budgetRanges[6]);const[message,setMessage]=useState('');
async function load(){try{const s=getSupabaseBrowserClient();const{data:{user}}=await s.auth.getUser();if(!user){window.location.href='/connexion';return;}const{data:profile}=await s.from('profiles').select('first_name,last_name').eq('id',user.id).maybeSingle();setUserName([profile?.first_name,profile?.last_name].filter(Boolean).join(' '));const{data,error}=await s.from('projects').select('id,title,status,service_type,city,updated_at').order('updated_at',{ascending:false});if(error)throw error;setProjects(data||[]);}catch(e){setMessage(e instanceof Error?e.message:'Chargement impossible.')}finally{setLoading(false)}}
useEffect(()=>{load()},[]);
async function create(e:FormEvent){e.preventDefault();setMessage('');try{const s=getSupabaseBrowserClient();const{data:{user}}=await s.auth.getUser();if(!user)throw new Error('Session expirée.');const{error}=await s.from('projects').insert({user_id:user.id,title,service_type:service,city:city||null,budget_range:budget,status:'draft'});if(error)throw error;setTitle('');setCity('');setShow(false);await load();}catch(e){setMessage(e instanceof Error?e.message:'Création impossible.')}}
async function signOut(){const s=getSupabaseBrowserClient();await s.auth.signOut();window.location.href='/';}
if(loading)return <div className="dashboard-state">Chargement de votre espace…</div>;
return <div className="dashboard"><aside className="dashboard-side"><div><p className="eyebrow">Espace client</p><strong>{userName||'Mon compte'}</strong></div><nav><Link href="/espace-client">Mes projets</Link><Link href="/espace-client/profil">Mon profil</Link><Link href="/espace-client/notifications">Notifications</Link></nav><button className="text-button" onClick={signOut}>Se déconnecter</button></aside><section className="dashboard-main"><div className="dashboard-head"><div><p className="eyebrow">Vos dossiers</p><h1>Bonjour{userName?` ${userName.split(' ')[0]}`:''}.</h1><p>Suivez vos projets et retrouvez leur prochain jalon.</p></div><button className="button-primary" onClick={()=>setShow(!show)}>+ Nouveau projet</button></div>{message&&<p className="form-message">{message}</p>}{show&&<form className="form-card compact" onSubmit={create}><h2>Nouveau projet</h2><label>Nom du projet<input required placeholder="Ex. Salon — maison familiale" value={title} onChange={e=>setTitle(e.target.value)}/></label><div className="form-grid"><label>Prestation<select value={service} onChange={e=>setService(e.target.value as typeof service)}>{services.map(s=><option key={s}>{s}</option>)}</select></label><label>Ville<input value={city} onChange={e=>setCity(e.target.value)}/></label></div><label>Budget indicatif<select value={budget} onChange={e=>setBudget(e.target.value as typeof budget)}>{budgetRanges.map(b=><option key={b}>{b}</option>)}</select></label><button className="button-primary">Créer le brouillon</button></form>}<div className="project-list">{projects.length===0?<div className="empty-card"><h2>Aucun projet pour le moment</h2><p>Créez votre premier dossier pour commencer.</p></div>:projects.map(p=><article className="project-row" key={p.id}><div><span className="status-pill">{labels[p.status]||p.status}</span><h2>{p.title}</h2><p>{[p.service_type,p.city].filter(Boolean).join(' · ')||'Projet en préparation'}</p></div><time>{new Date(p.updated_at).toLocaleDateString('fr-FR')}</time></article>)}</div></section></div>}
